## YAML Template.
---
spring:
    application:
        name: eurekaserver
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  serviceUrl:
    defaultZone: http://localhost:8761  

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.notix: DEBUG
    org.springframework.cloud.netflix.eureka: TRACE
    